name: second pipeline
on:
  push:
  workflow_dispatch:
    inputs:
      environment: 
        description: 'provide the env'
        requered: true
        default: 'dev'
        
    

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
        run: |
          echo "the default env is: ${{ github.event.inputs.environment }} environment"
