name: second pipeline
on:
  workflow_dispatch:
  push:
    inputs:
      environment: 
        description: 'provide the env'
        requered: true
        default: 'patch-1'
        
    

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "the default env is: ${{ on.workflow_dispatch.inputs.environment }} "
