name: second pipeline
on: push

jobs: 
    job1:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v5
            - name: locate the path
              run: pwd; ls
    