name: second pipeline
on:
  push

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      npm_version: ${{ steps.node_version.outputs.npm_version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Locate the path
        run: |
          pwd
          ls

      - name: Setup Node.js
        uses: actions/setup-node@v6

      - name: Check npm version
        id: node_version
        run: |
          echo "npm_version=$(npm --version)" >> $GITHUB_OUTPUT

      - name: Print npm version (from step output)
        run: |
          echo "The npm version is ${{ steps.node_version.outputs.npm_version }}"

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Print version from job1
        run: |
          echo "Goran and node version is: ${{ needs.job1.outputs.npm_version }}"
